### ISSUE TITLE
Remove deprecated MassaNodeServer flag

### ISSUE THREAD

**Issue by unholy0X** [massalabs/station#1026]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by thomas-senechal** [comment]
Hi ! 

Why are those flags deprecated ? 

I see that they are not used since : https://github.com/massalabs/station/pull/859 ([removed here](https://github.com/massalabs/station/pull/859/files#diff-17918c720975bf73ba2f791f5a86f0fb994160b8cdecc06d9c153243577704d3L94-L98)) but the linked issue does not mention this removal: https://github.com/massalabs/station/issues/851

So I'm asking, is it a mistake and we should fix those flags ? Or was it intended and so, we need to remove those flags (and associated variables) ? If it has been decided as a team, could you please send me the link to the discussion ?

IMO, we should fix those flags since, as a developper, it's really useful to restart MassaStation on a different network to test features really fast

**Comment by B-Naoufal** [comment]
> Hi !
> 
> Why are those flags deprecated ?
> 
> I see that they are not used since : #859 ([removed here](https://github.com/massalabs/station/pull/859/files#diff-17918c720975bf73ba2f791f5a86f0fb994160b8cdecc06d9c153243577704d3L94-L98)) but the linked issue does not mention this removal: #851
> 
> So I'm asking, is it a mistake and we should fix those flags ? Or was it intended and so, we need to remove those flags (and associated variables) ? If it has been decided as a team, could you please send me the link to the discussion ?
> 
> IMO, we should fix those flags since, as a developper, it's really useful to restart MassaStation on a different network to test features really fast

there is no link to the discussion, because it was done over a voice chat with the senior dev lead , and we agreed that config_network.yaml is enough for your use case , you just need to add `default`tag to the network you want to start station with , also you can use the switch button or call directly the endpoint from your terminal , so far you have 3 options to restart MassaStation on a different network to test features , but if you think you really need this feature lets discuss again with the senior lead dev.
