### ISSUE TITLE
Module store page - size of the module info box isn't correct

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1027]
**The problem(s)**
As a user, when I go on the module store page, I want to see 80 characters displayed as this is the rule we enforce on the module store so we MUST show all the characters. 

<img width="1512" alt="image" src="https://github.com/massalabs/station/assets/109611779/eab04839-18b5-4a67-8f17-ff2a2bc657fe">

**To Reproduce**
1. Just go on the module store and check the Massa node-manager info. 
2. Check the info contains on the store json. The description is 79 characters

**Expected behavior(s)**
We should display all the 80 characters sentence.
(or change the rule on the store but we must be consistent)

**Screenshots**
see above

**MassaStation version**
v0.2.5

**Comment by SlnPons** [comment]
cc @pivilartisant

**Comment by pivilartisant** [comment]
the problem : we already have limited the chars to 80 ->

```
// 80 is the max str length
export function truncate(content: string) {
  return content.length > 80 ? `${content.slice(0, 80)}...` : content;
}
```

But the problem is not the limit, it's the size of the plugin box : 
<img width="437" alt="Screenshot_2023-07-19_at_16 00 59" src="https://github.com/massalabs/station/assets/90157528/11b68279-49a6-4e0e-93c6-9975060bc8c4">

Which cannot fit our 80 characters... 

Proposed solution : we make the plugin boxes bigger in width or height depending on the most esthetic choice :)

**Comment by gregLibert** [comment]
This issue should be addressed during the plugin rework. @SlnPons, please let me know if you think my cleanup was excessive.
