### ISSUE TITLE
Thyra advanced logger

### ISSUE THREAD

**Issue by peterjah** [massalabs/station#460]
**Context**
- 1st need:

The idea is to have different log levels (like info, debug, warning....) that we can enable or not, probably using environment variables.
By default, debug logs should be not displayed

- 2nd need:

To be able to track bugs detected by users, it would be nice to have a way to retrieve theirs Thyra logs.
Especially when Thyra is launched from the icon, we need a way to access the logs (because there is no open terminal)
Al log file should be written, with logRotation enabled

**Technical details**
Use a Logger library like
https://pkg.go.dev/go.uber.org/zap or https://github.com/sirupsen/logrus

**QA testing**
Test the different log levels and check if log file exists

**Comment by Thykof** [comment]
We implemented our own logger package.

follow up issue to improve it: https://github.com/massalabs/station/issues/1191

---

> To be able to track bugs detected by users, it would be nice to have a way to retrieve theirs Thyra logs.
Especially when Thyra is launched from the icon, we need a way to access the logs (because there is no open terminal)
Al log file should be written, with logRotation enabled

this need is not covered by any PR nor any issue

**Comment by gregLibert** [comment]
Is already done
