### ISSUE TITLE
Windows - Massa Station is not in start menu

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station#767]
**The problem(s)**
When I search for massa station from the start menu, the only things found is the installer.

**To Reproduce**

**Expected behavior(s)**

**Screenshots**

**Thyra version**
The version of Thyra the bug is present in.

**Desktop (please complete the following information):**
windows 11
 
 **Any other useful info**

**Comment by thomas-senechal** [comment]
Expected since https://github.com/massalabs/thyra/pull/745 still hasn't been merged yet

**Comment by SlnPons** [comment]
@LucasF243 could you test Massa Station installation on your computer and record your screen please? 
It will enable us to see all the steps of the process easily as we've got multiple "bug" on windows. 

Thanks a lot :)

**Comment by thomas-senechal** [comment]
Please make sure to test using [v0.2.3](https://github.com/massalabs/station/releases/tag/v0.2.3) or above since it's this version that adds the shortcuts.

**Comment by maxime-carabina** [comment]
> @LucasF243 could you test Massa Station installation on your computer and record your screen please? It will enable us to see all the steps of the process easily as we've got multiple "bug" on windows.
> 
> Thanks a lot :)

Hey @SlnPons, I've just tested it and it works for me.
There's just a little problem with the logo because it doesn't appear.

On the desktop :
![image](https://github.com/massalabs/station/assets/72019005/b4244121-408b-471d-9477-bf1b4879f0e8)
![image](https://github.com/massalabs/station/assets/72019005/9895fc61-1ded-4199-afdf-67edbabb48f5)



But in the applications list :
![image](https://github.com/massalabs/station/assets/72019005/f7497fa4-644a-49d4-975e-e9ffc8bb5a5a)

**Comment by maxime-carabina** [comment]
> I've tested it and it all works, I don't have a logo either. The icon tray works fine.

I will create an issue for that bug

**Comment by SlnPons** [comment]
Can you link it here please @maxime-carabina?
@thomas-senechal is the issue reported in comment above is expected because not tackled?

**Comment by thomas-senechal** [comment]
> @thomas-senechal is the issue reported in comment above is expected because not tackled?

This isn't expected, but I think I know why it's happening

On MacOS and Linux, we are using `fyne` to package the app as a `.App` for MacOS, and an archive on Linux that contains the icon and other stuff useful to add the icon for MassaStation on the App list. 
But on Windows, we cannot use `fyne` because it needs to rebuild the `.exe`, but it always fails. So we only use `go` to build the binary, which does not add a logo to the `.exe`. 

IMO, we need to find a way to add the icon to the binary after building it. 
[josephspurrier/goversioninfo](https://github.com/josephspurrier/goversioninfo) might be a solution, needs further investigation

**Comment by SlnPons** [comment]
@maxime-carabina when you linked the issue you created here, could you also add thomas' comment above in the description please? 
So the dev who will work on it have a started point :)

**Comment by maxime-carabina** [comment]
> @maxime-carabina when you linked the issue you created here, could you also add thomas' comment above in the description please? So the dev who will work on it have a started point :)

Yes! No problem

**Comment by SlnPons** [comment]
Closing this issue as another one has been opened to work out a solution about the logo not appearing :)
