### ISSUE TITLE
fix dashboard

### ISSUE THREAD

**Issue by lilyanB** [massalabs/station#822]
- The images are not being updated when we change the dark/ligth mode!
- heigth of the component is not good neither
- There's a diff between the height when the plugin is installed and not installed. The installed one is smaller.

**Comment by SlnPons** [comment]
**QA review output for the home page: (using the latest version of the main at 1:20pm)**

Overall it is SUPPEEEEEEER nice to see this page coming to life. Honestly guys, it's been almost a year that I'm working on this product with no front-end so pretty happy to see that :D :D :D 

>> Things to correct: 
* When I click on "Search Massa ecosystem" or "Explore module store", I am redirected to an error page. See screenshot below.
If I refresh the page, I am redirected to the "old" version of thyra.
<img width="1512" alt="image" src="https://github.com/massalabs/station/assets/109611779/3fc69b92-d0df-49dc-b78b-1cf393e17e06">
<img width="1512" alt="image" src="https://github.com/massalabs/station/assets/109611779/94e112fe-8ee8-449b-bafe-0fb4b56c9914">

* For the wallet installation, when I don't have the wallet installed and I click on "install". I need to wait a little bit and then the button + icon turn into colour (ie: activated mode) but I click on the "Launch" button I am redirected to an error page. 

If I refresh the page, I can access the wallet. 
<img width="1512" alt="image" src="https://github.com/massalabs/station/assets/109611779/7de67d3c-beac-4030-bfc2-4ddeaa880153">

Expected behaviour: 
1. When I click on "Launch", it opens a new tab. 
2. When I click on "Launch", a new tab opens with Massa Wallet page working 😅

* Change the name of the Wallet: currently "Massawallet"; expected: "Massa Wallet"
Sorry about that it's clearly a problem of design and stakeholders alignement... last minute change. 
<img width="385" alt="image" src="https://github.com/massalabs/station/assets/109611779/fab6a1b1-2c56-45fc-80c0-3719d68c38db">

* Change the sentence displayed when the wallet is not installed. 
Currently: 
<img width="389" alt="image" src="https://github.com/massalabs/station/assets/109611779/e3a67cc8-c558-49e0-9a79-f3c24b9676e9">

Expected: 
"Massa Wallet is not installed in your Station." 
To be consistent with the point above.

**Comment by Thykof** [comment]
PR to fix your first point: #835

**Comment by Thykof** [comment]
@SlnPons your second point is needs https://github.com/massalabs/station-store/pull/21

**Comment by Thykof** [comment]
@mazmassa component PluginWallet doesn't rerender when its props isActive change value, as the result it stays in state inactive even when it is installed.

I think we need to rework again Index.tsx component... let's see together because I don't understand the way the code wants to take.

**Comment by SlnPons** [comment]
See all errors in the console on this page ... this can't be consider done. 
Please have a look and solve these errors :)

**Comment by lilyanB** [comment]
@SlnPons these errors?
![image](https://github.com/massalabs/station/assets/91454320/a73ab141-8594-4de0-b8cd-41f179d0b73a)

**Comment by SlnPons** [comment]
@lilyanB nope. 
these ones, we should handle this nicely. Is it possible @Thykof ?
We're delivering a mainnet product here... not a PoC :)


![Image](https://github.com/massalabs/station/assets/109611779/61e8f716-bb36-4b65-bdc1-9a70f4b09a66)

**Comment by SlnPons** [comment]
@Thykof can you take the lead on this and look at these errors. Pierre S also reported them. 
Happy to help or discuss :)

**Comment by Thykof** [comment]
The application fetch the wallet API to display your account in the search page, upload sidepanel.

if you don't have the wallet installed, requests to it's API fail to 404 errors. This is expected. @mazmassa with useResource, do you know a way to no send these request if we now that the wallet is not installed?

**Comment by SlnPons** [comment]
Yep I understood what it does :)  
But as Pierre S also reported this as a problem I am wondering if we couldn't do sth... 
Could you check with him if he had an idea or simply what he thought about that? If as an experienced dev he wasn't expected to see that it's probs because we can do better ;)
