### ISSUE TITLE
[BUG] CA certificate on macOS are in two different directories

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station#890]
On the [GO side](https://github.com/massalabs/station/blob/main/pkg/certificate/certificate.go#L140-L142):  ${HOME}/Library/Application Support/
On the [installer side](https://github.com/massalabs/station/blob/main/installer/macos/scripts/postinstall#L13C30-L13C53): /etc/massastation/certs

This returned the following logs:
```
while handling SNI Hello request: while loading CA key: while reading key file from /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: open /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: permission denied2023/06/26 17:14:22 http: TLS handshake error from 127.0.0.1:53476: while handling SNI Hello request: while loading CA key: while reading key file from /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: open /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: permission denied
while handling SNI Hello request: while loading CA key: while reading key file from /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: open /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: permission denied2023/06/26 17:14:22 http: TLS handshake error from 127.0.0.1:53477: while handling SNI Hello request: while loading CA key: while reading key file from /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: open /Users/XXX/Library/Application Support/mkcert/rootCA-key.pem: permission denied
```

**Comment by gregLibert** [comment]
As this is a installation bug, I've changed its milestone.

**Comment by Thykof** [comment]
On the [GO side](https://github.com/massalabs/station/blob/main/pkg/certificate/certificate.go#L140-L142): ${HOME}/Library/Application Support/mkcert


the files in `${HOME}/Library/Application Support/mkcert` are generated by something (I have deleted them, run the massa station installer, launch the app, and it works because there are here.)

on go side we are looking for file rootCA-key.pem

on installer side, for cert-key.pem

If the problem was related to wrong path, you will not have `permission denied`, but `no such file or directory`.

However, I can reproduce the bug.

I continue investigating...

**Comment by gregLibert** [comment]
We had permission denied because the directory and the file were preexisting (previous install of Massa Station).

**Comment by Thykof** [comment]
`./mkcert -install` in the installation script creates in `~/Library/Application Support/mkcert`:
```
-r--------  1 root  staff   2.4K Jun 28 11:50 rootCA-key.pem
-rw-r--r--  1 root  staff   1.8K Jun 28 11:50 rootCA.pem
```

**Comment by SlnPons** [comment]
Hey @gregLibert is this the issue reported by Adrien please?
