### ISSUE TITLE
Add CA to firefox on windows

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station#961]
To install self generated CA on windows you need:

1. To get an NSS certutil binary
  1. get last version of tor tooling: https://dist.torproject.org/torbrowser/
  2. download mar-tool win64
2. Found you firefox profile :%APPDATA%\Mozilla\Firefox\Profiles\
3. For each of them add the certificate to the nss database: 
```
.\certutil.exe -A -n "massaStation" -t "C,," -d "C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\q2uvaj94.default-release" -i "C:\Users\xxx\AppData\local\mkcert\rootCA.pem"
```

Note: windows certutil and the one provided by tor are not offering the same functionalities

**Comment by Thykof** [comment]
Here is the bug report:

**The problem(s)**

After installing Massa Station, I cant't navigate to https://station.massa/ on firefox, 

**Expected behavior(s)**

I should be able to use Massa Station on Firefox on Windows

**Screenshots**
![image](https://github.com/massalabs/station/assets/11590067/1ab1f97d-1e64-4462-80fe-375b555bc2bc)
(sorry it's french)

**MassaStation version**
The version of MassaStation the bug is present in.

https://github.com/massalabs/station/releases/tag/v0.2.5

**Desktop (please complete the following information):**
 - OS: Windwos
 - Browser: Firefox
 
 **Any other useful info**
related issues:
- https://github.com/massalabs/station/issues/381
- https://github.com/massalabs/station/issues/758

**How to fix**
See the issue description

**Comment by thomas-senechal** [comment]
> I think we should download a specific version of mar-tools, so that we control the migration to a new version. This would avoid breaking things when a new version of mar-tools is released.

I agree ! 

> When you are talking about "update the mar-tools library alongside MassaStation" you talk about a user that update Massa Station on his laptop?

Yes, when a user performs an update of MassaStation using the installer, `mar-tools` can be updated with it

**Comment by gregLibert** [comment]
> I think we should download a specific version of mar-tools, so that we control the migration to a new version. This would avoid breaking things when a new version of mar-tools is released.

In this case, we should integrate these files with our source installer because only the latest versions of mar-tools can be accessed via https://dist.torproject.org/torbrowser/

**Comment by thomas-senechal** [comment]
Passed QA: Working perfectly
