### ISSUE TITLE
Installation - Install Massa Station on windows on any disk

### ISSUE THREAD

**Issue by Thykof** [massalabs/station#977]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

in script installer/windows/scripts/configure_acrylic.bat we should make the path of `acrylic_config` an argument of the script so we will always use the right directory even if the user installed MS on another disk (not C).

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by thomas-senechal** [comment]
Reopening because I found some issues with the current implementation.

If you select `C:\Program Files` (instead of `Program Files (x86)`), MassaStation is still installed in `Program Files (x86)` and Acrylic is installed in `C:\Program Files (x86)\Acrylic DNS Proxy`.

If you select `C:\MassaStation` (or any other disk), MS will be installed in the asked directory but Acrylic is installed in `C:\Program Files (x86)\Acrylic DNS Proxy`. Same for other directories in `C:` (or any other disk)

In any case, Acrylic is installed in `C:\Program Files (x86)\Acrylic DNS Proxy`

In my opinion:
- We can forget about the `C:\Program Files` / `C:\Program Files (x86)` issue because it might just be related to Windows forcing the installation directory depending on the targeted architecture of the binary (32 or 64bits)
- We should decide if we want to keep Acrylic in `C:\Program Files (x86)`, which is against User will, or if we want to also install Acrylic in the same directory as MassaStation

**Comment by Thykof** [comment]
So now the only remaining question is: should we install acrylic on the disk the user wants to install Massa Station. If no, then we can close this issue.
